from app.database.models import Location
from app.database.database import SessionLocal
from sqlalchemy.exc import IntegrityError


def seed_locations():
    session = SessionLocal()

    locations_data = [
        {"name": "Москвариум 1", "order": 1},
        {"name": "Москвариум 0", "order": 2},
        {"name": "Мастер классы", "order": 3},
        {"name": "Прекрасный помогатор", "order": 4},
        {"name": "Мультпарк", "order": 5},
        {"name": "Авиапарк", "order": 6},
        {"name": "Москвариум 3", "order": 7},
        {"name": "Луномосик", "order": 8},
    ]

    for loc in locations_data:
        existing = session.query(Location).filter_by(name=loc["name"]).first()
        if not existing:
            session.add(Location(**loc))

    try:
        session.commit()
        print("Локации успешно добавлены!")
    except IntegrityError:
        session.rollback()
        print("Ошибка при добавлении локаций.")
    finally:
        session.close()

